In [365]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import json

In [331]:
def makaan_scraper_v2():
    '''scrapes the popular real estate website makaan.com to get data such as coordinates, property type, locality, area'''
    import requests
    from bs4 import BeautifulSoup
    import numpy as np
    import pandas as pd
    url = 'https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city'
    response = requests.get(url)
    if response.ok:
        soup = BeautifulSoup(response.text, "lxml")
        pagenav = soup.select(".pagination > :nth-of-type(1) >:nth-of-type(7)>:nth-of-type(1)")
        num_pages = int(pagenav[0].text)
    lats=[]
    longs=[]
    seller_type=[]
    no_beds=[]
    layout_type=[]
    property_type=[]
    locality_type=[]
    area_value=[]
    area_unit=[]
    furnishing=[]
    prices = []
    #n_bathrooms=[]
    for i in range(1,num_pages):
        url = 'https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city' + '?page='+str(i)
        response = requests.get(url)
        if response.ok:
            soup = BeautifulSoup(response.text, "lxml")

            latitudes = [soup.find_all(attrs={"itemprop": "latitude"})] 
            lats.extend([str(latitude)[15:25] for latitude in latitudes[0]]) 

            longitudes = [soup.find_all(attrs={"itemprop": "longitude"})] 
            longs.extend([str(longitude)[15:25] for longitude in longitudes[0]]) 

            sellers = soup.find_all(attrs={"class": "seller-type"})
            seller_type.extend([seller.text for seller in sellers])

            titles= soup.select('a.typelink')
            titles = [title.text.split() for title in titles]

            no_beds.extend([title[0] for title in titles])
            layout_type.extend([title[1] for title in titles])
            property_type.extend([' '.join(title[2:]) for title in titles])

            localities = soup.find_all(attrs={"itemprop": "addressLocality"})
            locality_type.extend([locality.text for locality in localities])

            areas = soup.find_all(attrs={"class": "size"})
            area_value.extend([area.text for area in areas])

            units = [soup.select(".size ~ .lbl")] 
            area_unit.extend([unit.text for unit in units[0]])

            ftypes = soup.find_all(attrs={"class": "hcol w44"})
            furnishing.extend([ftype.text for ftype in ftypes])
            
            pricex = soup.find_all(attrs={"itemprop": "offers"})
            prices.extend([price.text for price in pricex])
            #bathrooms = soup.find_all(attrs={"title": "bathrooms"})
            #n_bathrooms.extend([broom.text for broom in bathrooms])
            print(i)    
    data=[lats,longs,seller_type,no_beds,layout_type,property_type,locality_type,area_value,area_unit,furnishing,prices]
    columns = ('latitude','longitude','seller','bedrooms','layout','property_type','locality','area','units','furnishing','rent')
    df = pd.DataFrame(data,columns).transpose() 
    return df

In [443]:
def makaan_scraper_v1():
    '''scrapes the popular real estate website makaan.com to get data such as coordinates, property type, locality, area'''
    import requests
    from bs4 import BeautifulSoup
    import numpy as np
    import pandas as pd
    import json
    url = 'https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city'
    response = requests.get(url)
    if response.ok:
        soup = BeautifulSoup(response.text, "lxml")
        pagenav = soup.select(".pagination > :nth-of-type(1) >:nth-of-type(7)>:nth-of-type(1)")
        num_pages = int(pagenav[0].text)
        mainlist=[]
    for i in range(1,num_pages):
        url1 = 'https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city' + '?page='+str(i)
        response = requests.get(url1)
        if response.ok:
            soup = BeautifulSoup(response.text, "lxml")
            cards = soup.select(".cardWrapper > script")
            for j in range(len(cards)):
                attrs = json.loads(cards[j].text)
                mylist=[attrs['latitude'],attrs['longitude'],attrs['bedrooms'],attrs['sellerType'],attrs['propertyType'],attrs['localityName'],attrs['suburbName'],attrs['size'].split()[0],('').join(attrs['size'].split()[1:]),attrs['price']]
                mainlist.append(mylist)
        print(i)        

            
    
    columns = ('latitude','longitude','bedrooms','seller','property_type','locality','suburb','area','units','rent')
    df = pd.DataFrame(mainlist,columns=columns)
    return df

In [444]:
df = makaan_scraper_v1()
df.to_csv('hyd_rents')

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549

,latitude,longitude,bedrooms,seller,property_type,locality,suburb,area,units,rent
0,17.479078,78.320862,1,OWNER,Apartment,Serilingampally,Hyderabad West,320,sqft,6720
1,17.395611,78.434128,2,OWNER,Apartment,Dilsukh Nagar,Hyderabad Central,"1,500",sqft,14500
2,17.375957,78.537056,2,OWNER,Apartment,Dilsukh Nagar,Hyderabad Central,"1,050",sqft,13000
3,17.462992,78.357643,1,OWNER,Apartment,Kondapur,Hyderabad West,150,sqft,10000
4,17.422832,78.458504,2,OWNER,Apartment,Somajiguda,Hyderabad Central,"1,000",sqft,18000
...,...,...,...,...,...,...,...,...,...,...
10975,17.390228,78.340256,3,AGENT,Apartment,Kokapeta Village,Other,"1,300",sqft,32000
10976,17.440525,78.392296,3,AGENT,Apartment,Madhpal,Other,"2,000",sqft,34000
10977,17.439516,78.496460,1,AGENT,Independent Floor,Shivaji Nagar,Other,600,sqft,7500
10978,17.494793,78.399643,1,AGENT,Apartment,Kukatpally,Hyderabad West,"1,050",sqft,8000
10979,17.465866,78.352112,2,AGENT,Apartment,Kondapur,Hyderabad West,"1,800",sqft,39000

Kondapur                    1382
Madhapur                     624
Kukatpally                   608
Manikonda                    453
Gachibowli                   414
                            ...
Jayanagar New Bowenpally       1
Buddha Nagar                   1
Jalapalli                      1
Pragathi Nagar Main            1
Huda Colony                    1
Name: locality, Length: 506, dtype: int64

https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=1
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=2
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=3
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=4
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=5
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=6
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=7
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=8
https://www.makaan.com/hyderabad-residential-property/rent-property-in-hyderabad-city?page=9

[]